version: '3.8'
services:
  nginx:
    build: #usually we would specify an image name but in this case the nginx service was created with his own dockerfile
      context: .
      dockerfile: nginx.dockerfile

    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - php

  mysql:
    image: mysql:8.0.31

    ports:
      - 3307:3306

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html #bydefault composer will try to run commands inside it's own folder that's why we need to specify the working directory
